//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoP9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Total
    {
        public int id_total { get; set; }
        public int vehiculo { get; set; }
        public Nullable<int> total1 { get; set; }
    
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
