//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoP9.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculos()
        {
            this.Total = new HashSet<Total>();
        }
        [Display(Name = "ID")]
        public int id_vehiculo { get; set; }

        [Display(Name = "PLACAS:")]
        public string placa { get; set; }

        [Display(Name = "MARCA:")]
        public string marca { get; set; }


        [Display(Name = "MODELO:")]
        public string modelo { get; set; }


        [Display(Name = "AÑO CREACIÓN:")]
        [Range(2009, 2017, ErrorMessage = "El año del vehiculo debe estar entre  2009 y 2017")]
        public int año_creacion { get; set; }


        [Display(Name = "CILINDROS:")]
        [Range(4, 6, ErrorMessage = "Debe ingresar 4 y 6 cilindros")]
        public int cilindros { get; set; }

        [Display(Name = "CANT. LLANTAS:")]
        [Range(4, 8, ErrorMessage = "La cantidad de llantas debe de estar entre 4 y 8")]
        public int cantidad_llantas { get; set; }

        [Display(Name = "MOTOR C.C:")]
        public int motor { get; set; }

        [Display(Name = "CLIENTE:")]
        public int id_cliente { get; set; }

        [Display(Name = "UBICACION:")]
        public int ubicacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Total> Total { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
    }
}
